services:
  # PHP Application
  lzds-system-legacy:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: lzds-system-legacy
    container_name: lzds-system-legacy
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    deploy:
        resources:
            limits:
                memory: 2G
            reservations:
                memory: 1G      

  # Nginx Web Server
  nginx-lzds-system-legacy:
    image: nginx:alpine
    container_name: nginx-lzds-system-legacy
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - lzds-system-legacy
    deploy:
        resources:
            limits:
                memory: 2G
            reservations:
                memory: 1G